# Generated by Django 5.1.4 on 2024-12-13 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('join_auth', '0009_remove_userprofile_selected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('initials', models.CharField(blank=True, max_length=5)),
                ('initialsColor', models.CharField(blank=True, max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dueDate', models.DateField()),
                ('subtasks', models.JSONField(default=list)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('category', models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], max_length=50)),
                ('column', models.CharField(choices=[('toDo', 'To Do'), ('awaitingFeedback', 'Awaiting Feedback'), ('inProgress', 'In Progress'), ('done', 'Done')], max_length=20)),
                ('assignedTo', models.ManyToManyField(related_name='tasks', to='join_auth.userprofile')),
            ],
        ),
    ]
