# Generated by Django 5.1.4 on 2024-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='12345670', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='initials',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='initialsColor',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
