# Generated by Django 5.1.4 on 2024-12-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_auth', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='12345670', max_length=15),
        ),
    ]
