# Generated by Django 5.1.4 on 2024-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_auth', '0005_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email already taken.'}, max_length=254, unique=True),
        ),
    ]
