# Generated by Django 5.1.4 on 2024-12-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_auth', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='initials',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='initialsColor',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='12345670', max_length=15),
        ),
    ]
