# Generated by Django 5.1.4 on 2024-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_auth', '0009_remove_userprofile_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
