# Generated by Django 5.1.4 on 2024-12-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_auth', '0010_userprofile_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='123456704343', max_length=15),
        ),
    ]
